import {deliverMail,mailConfigured} from '@/lib/mail';
import {readJson,RequestError} from '@/lib/security';
import {NextResponse} from 'next/server';
import {revalidatePath} from 'next/cache';
import {z} from 'zod';
import {isAdmin,database,sameOrigin} from '@/lib/admin';
import fields from '@/lib/content-fields.json';
const serviceSchema=z.object({id:z.string().uuid().optional(),title:z.string().min(2).max(160),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(180),short_description:z.string().max(3000),description:z.string().max(15000).optional(),active:z.boolean(),display_order:z.number().int().min(0).max(10000)});
export async function GET(){if(!await isAdmin())return NextResponse.json({error:'Sign in required'},{status:401});try{const db=database();const [content,services,enquiries,mail]=await Promise.all([db.from('site_settings').select('setting_value').eq('setting_group','website').eq('setting_key','content').maybeSingle(),db.from('services').select('id,title,slug,short_description,description,active,display_order').order('display_order'),db.from('enquiries').select('id,reference_number,name,email,phone,message,service_label,status,created_at').order('created_at',{ascending:false}).limit(100),db.from('site_settings').select('setting_key,setting_value,updated_at').eq('setting_group','enquiry_mail').order('updated_at',{ascending:false}).limit(100)]);if(content.error||services.error||enquiries.error||mail.error)throw new Error();return NextResponse.json({content:content.data?.setting_value||{},services:services.data,enquiries:enquiries.data,mail:(mail.data||[]).map(row=>({reference:row.setting_key,status:row.setting_value.status,attempts:row.setting_value.attempts,updated_at:row.updated_at}))},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'Unable to load admin data. Check your Supabase configuration.'},{status:500});}}
export async function PUT(req:Request){if(!sameOrigin(req))return NextResponse.json({error:'Invalid origin'},{status:403});if(!await isAdmin())return NextResponse.json({error:'Sign in required'},{status:401});try{const body=await readJson(req,256000);const db=database();if(body.type==='content'){const values=z.record(z.string(),z.string().max(15000)).parse(body.values);const allowed=new Map(fields.map(f=>[f.id,f]));for(const [key,value] of Object.entries(values)){if(!allowed.has(key))throw new Error('Unknown content field.');if(allowed.get(key)?.type==='social'&&value){const domain=key==='social.instagram'?'instagram.com':key==='social.facebook'?'facebook.com':'linkedin.com';const url=new URL(value);if(url.protocol!=='https:'||!(url.hostname===domain||url.hostname.endsWith('.'+domain)))throw new Error('Enter the HTTPS profile URL for the selected social network.');}if(allowed.get(key)?.type==='image'&&value&&!/^\/(?![\/\\])/.test(value)&&!/^https:\/\//.test(value))throw new Error('Use a local image path or an HTTPS image URL.');}const {error}=await db.from('site_settings').upsert({setting_group:'website',setting_key:'content',setting_value:values},{onConflict:'setting_group,setting_key'});if(error)throw new Error('Unable to save page content.');}else if(body.type==='retry-mail'){const reference=z.string().regex(/^CBX-ENQ-[0-9]{4}-[a-fA-F0-9-]{8,36}$/).parse(body.reference);if(!mailConfigured())return NextResponse.json({error:'Configure Zoho SMTP before retrying email.'},{status:503});if(!await deliverMail(reference))return NextResponse.json({error:'Email remains pending. Check Zoho configuration and delivery logs.'},{status:503});}else if(body.type==='service'){const value=serviceSchema.parse(body.value);const {error}=await db.from('services').upsert(value);if(error)throw new Error('Unable to save service. Make sure its URL slug is unique.');}else if(body.type==='enquiry'){const value=z.object({id:z.string().uuid(),status:z.enum(['NEW','CONTACTED','IN_PROGRESS','QUALIFIED','CLOSED','SPAM'])}).parse(body.value);const {error}=await db.from('enquiries').update({status:value.status}).eq('id',value.id);if(error)throw new Error('Unable to update enquiry.');}else return NextResponse.json({error:'Unknown update type'},{status:400});revalidatePath('/','layout');return NextResponse.json({ok:true});}catch(e){if(e instanceof RequestError)return NextResponse.json({error:e.message},{status:e.status});return NextResponse.json({error:e instanceof z.ZodError?'Please check the fields and try again.':e instanceof Error?e.message:'Unable to save changes.'},{status:400});}}
