import CompanyPrinciples from '@/components/CompanyPrinciples';
import ServiceGrid from '@/components/ServiceGrid';
import {Content,CmsImage,HeroImage} from '@/components/Cms';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Cloud, Monitor, Network } from 'lucide-react';
import { getServices } from '@/lib/data';
const sectors = [
  { title: 'IT & cloud infrastructure', text: 'Build a dependable foundation with cloud operations, hosting, business email and connected systems.', icon: Cloud },
  { title: 'Digital experiences', text: 'Bring your ideas to life with responsive websites and applications shaped around your business.', icon: Monitor },
  { title: 'Connected workplaces', text: 'Keep your team productive with managed IT, software support and contractual infrastructure maintenance.', icon: Network },
];
export default async function Home() {
 const services = await getServices();
 return <main>
  <section className="hero"><HeroImage/><div className="hero-shade"/><div className="wrap hero-content"><span className="eyebrow light"><Content id="home.text1">Cubixtop India · Technology with purpose</Content></span><h1><Content id="home.text2">Build. Connect.</Content><br/><Content id="home.text3">Grow with</Content><br/><span><Content id="home.text4">confidence.</Content></span></h1><div className="hero-bottom"><Link className="text-link" href="/services"><Content id="home.text5">Discover our solutions </Content><ArrowUpRight size={22}/></Link><p><Content id="home.text6">Your business has ambition.</Content><br/><Content id="home.text7">We bring the technology to move it forward.</Content></p></div></div><a href="#services" className="hero-scroll" aria-label="Scroll to our services"><span>Scroll to explore</span><span className="scroll-line"/></a><div className="hero-caption"><Content id="home.text8">IT INFRASTRUCTURE / DIGITAL / BUSINESS SOLUTIONS</Content></div></section>
  <Link href="/contact" className="contact-strip"><div className="wrap"><span><Content id="home.text9">Good things start with a conversation.</Content></span><strong><Content id="home.text10">Let’s work together </Content><ArrowUpRight/></strong></div></Link>
  <section className="section"><div className="wrap intro-grid"><span className="eyebrow"><Content id="home.text11">01 / Who we are</Content></span><div><h2 className="section-title"><Content id="home.text12">One partner.</Content><br/><Content id="home.text13">A world of possibilities.</Content></h2><p className="lead"><Content id="home.text14">Technology should make your business simpler. We bring your IT, digital and workplace needs together with practical solutions and personal support.</Content></p><div className="principles"><div><h3><Content id="home.text15">Our approach</Content></h3><p><Content id="home.text16">Understand your needs. Find the right solution. Help you move forward.</Content></p></div><div><h3><Content id="home.text17">What matters to us</Content></h3><p><Content id="home.text18">Clear communication. Reliable service. Technology that works for you.</Content></p></div></div><Link className="text-link dark-link" href="/about"><Content id="home.text19">Meet Cubixtop India </Content><ArrowUpRight size={20}/></Link></div></div></section>
  <section className="section capabilities"><div className="wrap"><div className="section-heading"><div><span className="eyebrow"><Content id="home.text20">02 / Our expertise</Content></span><h2 className="section-title"><Content id="home.text21">Built around</Content><br/><Content id="home.text22">your business.</Content></h2></div><Link className="text-link dark-link" href="/services"><Content id="home.text23">Explore all services </Content><ArrowUpRight size={20}/></Link></div><div className="feature-grid"><Link href="/services/cloud-operations-and-setup" className="feature-card"><CmsImage id="home.image37" src="/images/servers.jpg" alt="Network equipment in a business server room"/><div><span><Content id="home.text24">INFRASTRUCTURE & SUPPORT</Content></span><h3><Content id="home.text25">A stronger foundation.</Content></h3><ArrowUpRight/></div></Link><Link href="/services/custom-application-development" className="feature-card"><CmsImage id="home.image38" src="/images/software.jpg" alt="Software development workspace with a laptop and monitor"/><div><span><Content id="home.text26">WEBSITES & APPLICATIONS</Content></span><h3><Content id="home.text27">Your next possibility.</Content></h3><ArrowUpRight/></div></Link></div><div className="sector-grid">{sectors.map(({title,text,icon:Icon},i)=><article key={title}><Icon size={32} strokeWidth={1.3}/><h3><Content id={`home.sector${i}.title`}>{title}</Content></h3><p><Content id={`home.sector${i}.text`}>{text}</Content></p></article>)}</div></div></section>
  <section id="services" className="section service-grid-section"><div className="wrap"><div className="service-grid-heading"><div><span className="eyebrow"><Content id="home.text28">03 / What we do</Content></span><h2 className="section-title"><Content id="home.text29">The right expertise.</Content><br/><Content id="home.text30">At every step.</Content></h2><p className="lead"><Content id="home.text31">Contractual IT infrastructure maintenance and software solutions for every business.</Content></p></div></div><ServiceGrid services={services}/></div></section>
  <section className="approach"><CmsImage id="home.image39" src="/images/it-team.jpg" alt="Technology professionals collaborating on laptops"/><div className="approach-copy"><span className="eyebrow"><Content id="home.text32">04 / Our way</Content></span><h2 className="section-title"><Content id="home.text33">Better technology.</Content><br/><Content id="home.text34">Better everyday.</Content></h2><p className="lead"><Content id="home.text35">A well-connected workplace makes room for great work. We help bring the systems, tools and support together so you can focus on what comes next.</Content></p><Link href="/about" className="text-link dark-link"><Content id="home.text36">Discover our approach </Content><ArrowRight size={20}/></Link></div></section>
 <CompanyPrinciples compact/></main>;
}
