'use client';
import {socialProfiles} from '@/lib/social-profiles';
import {Instagram,Facebook,Linkedin,Pause,Play} from 'lucide-react';
import {createContext,useContext,useState,useEffect} from 'react';
const Context=createContext<Record<string,string>>({});
export function CmsProvider({values,children}:{values:Record<string,string>,children:React.ReactNode}){return <Context.Provider value={values}>{children}</Context.Provider>}
export function Content({id,children}:{id:string,children:React.ReactNode}){const values=useContext(Context);return <>{values[id]??children}</>}
export function CmsImage({id,src,alt,...props}:{id:string,src:string,alt:string,className?:string,loading?:'lazy'|'eager'}){const values=useContext(Context);return <img {...props} src={values[id]||src} alt={values[id+'.alt']??alt}/>}
const bannerSlides=[['/images/code.jpg','Software development'],['/images/software.jpg','Business applications'],['/images/digital.jpg','Data and digital solutions'],['/images/servers.jpg','IT infrastructure'],['/images/it-team.jpg','Technology collaboration']];
export function HeroImage(){const values=useContext(Context);const[active,setActive]=useState(0),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false);useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);useEffect(()=>{if(paused||reduced)return;const timer=setInterval(()=>{if(!document.hidden)setActive(index=>(index+1)%bannerSlides.length);},4000);return()=>clearInterval(timer);},[paused,reduced]);return <><div className="hero-slides" aria-hidden="true">{bannerSlides.map(([src,label],i)=><img key={src} src={values[i===0?'home.heroImage':`home.slide${i+1}`]||src} alt="" className={i===active?'hero-slide active':'hero-slide'} fetchPriority={i===0?'high':'auto'}/>)}</div><div className="hero-slide-controls"><div role="group" aria-label="Banner images">{bannerSlides.map(([,label],i)=><button key={label} onClick={()=>setActive(i)} aria-label={`Show ${label}`} aria-pressed={active===i} className={active===i?'active':''}/>)}</div><button onClick={()=>setPaused(!paused)} disabled={reduced} aria-label={paused?'Play banner slideshow':'Pause banner slideshow'}>{paused||reduced?<Play size={16}/>:<Pause size={16}/>}</button></div></>}

export function SocialLinks(){const values=useContext(Context);const networks=[{key:'instagram',label:'Instagram',icon:Instagram,domain:'instagram.com'},{key:'facebook',label:'Facebook',icon:Facebook,domain:'facebook.com'},{key:'linkedin',label:'LinkedIn',icon:Linkedin,domain:'linkedin.com'}];const links=networks.map(n=>{try{const url=new URL(values['social.'+n.key]??socialProfiles[n.key]??'');return {...n,enabled:url.protocol==='https:'&&(url.hostname===n.domain||url.hostname.endsWith('.'+n.domain))};}catch{return {...n,enabled:false};}});return <nav className="social-links" aria-label="Follow Cubixtop">{links.map(({key,label,icon:Icon,enabled})=>enabled?<a key={key} href={values['social.'+key]??socialProfiles[key]} target="_blank" rel="noopener noreferrer" aria-label={'Cubixtop on '+label}><Icon size={19}/><span>{label}</span></a>:<span key={key} className="social-unconfigured" title={label+' profile link will be available soon'}><Icon size={19}/><span>{label}</span></span>)}</nav>}
