'use client';
import {serviceCatalog} from '@/lib/service-catalog';
import {useState, type FormEvent} from 'react';
import {ArrowUpRight,CheckCircle2,Phone,MessageCircle,LoaderCircle,LockKeyhole} from 'lucide-react';
export default function EnquiryForm({service='General enquiry'}:{service?:string}){
 const [pending,setPending]=useState(false); const [error,setError]=useState(''); const [reference,setReference]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError('');const body=Object.fromEntries(new FormData(event.currentTarget));body.website=body.contact_guard||'';delete body.contact_guard;try{const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!response.ok||!data?.reference){if(response.status===429){const minutes=Math.max(1,Math.ceil(Number(response.headers.get('retry-after')||60)/60));throw new Error(`Please wait ${minutes} minute${minutes===1?'':'s'} before sending another enquiry, or contact us below.`);}throw new Error(data?.error||'Unable to connect right now. Please try again or use call / WhatsApp below.');}setReference(data.reference);}catch(error){setError(error instanceof Error?error.message:'Unable to connect. Please try again.');}finally{setPending(false);}}
 const contactOptions=<div className="enquiry-contact-options"><a href="tel:+919481317929"><Phone size={18}/>Call us</a><a href="https://wa.me/919481317929?text=Hello%20Cubixtop%2C%20I%20would%20like%20to%20discuss%20my%20requirement." target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>Chat on WhatsApp</a></div>;
 if(reference)return <div className="success-message enquiry-success"><div role="status"><CheckCircle2 size={42} aria-hidden="true"/><h3>Thank you for your enquiry!</h3><p>We’ve received your message and will get in touch shortly.</p><p className="enquiry-reference">Your reference: <strong>{reference}</strong></p></div><p className="mt-6 text-sm">Want to speak with us now?</p>{contactOptions}<a className="enquiry-phone" href="tel:+919481317929">+91 9481 317 929</a></div>;

 return <form onSubmit={submit} className="enquiry-form modern-enquiry-form" aria-busy={pending}><div className="form-honeypot" aria-hidden="true"><label>Leave this blank<input name="contact_guard" tabIndex={-1} autoComplete="off" data-lpignore="true" data-1p-ignore="true"/></label></div><div className="form-pair"><label>Full name<input name="name" required minLength={2} maxLength={120} autoComplete="name" placeholder="Your name"/></label><label>Phone number<input name="phone" type="tel" inputMode="tel" required minLength={6} maxLength={30} autoComplete="tel" placeholder="Your mobile number"/></label></div><label>Email address<input name="email" type="email" required autoComplete="email" placeholder="you@company.com"/></label><label>How can we help?<select name="service" defaultValue={service}>{Array.from(new Set([service,'General enquiry',...serviceCatalog.map(item=>item.title)])).map(s=><option key={s}>{s}</option>)}</select></label><label>Your message<textarea name="message" required minLength={3} maxLength={3000} placeholder="Tell us a little about your requirements…"/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={pending} className="btn" type="submit">{pending?'Sending your message…':'Let’s start a conversation'} {pending?<LoaderCircle className="enquiry-spinner" size={18}/>:<ArrowUpRight size={18}/>}</button><p className="enquiry-privacy"><LockKeyhole size={13} aria-hidden="true"/>Your details are used only to respond to your enquiry.</p>{error&&contactOptions}</form>;
}
