'use client';
import {useEffect,useRef} from 'react';
import {X,ArrowUpRight,Phone,MessageCircle} from 'lucide-react';
import EnquiryForm from './EnquiryForm';
export default function EnquiryModal({open,close,service}:{open:boolean,close:()=>void,service?:string}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open){ref.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;ref.current?.close();};}ref.current?.close();},[open]);
 return <dialog ref={ref} className="modal enquiry-dialog" aria-labelledby="enquiry-title" onCancel={close} onClick={e=>{if(e.target===ref.current)close();}}><div className="enquiry-dialog-grid"><aside className="enquiry-intro"><img src="/images/code.jpg" alt="" className="enquiry-intro-photo"/><div className="enquiry-intro-content"><span className="eyebrow light">Cubixtop India</span><h2>Great ideas.<br/>Better together<span>.</span></h2><p>Tell us what’s next for your business. We’ll help you find the right technology to get there.</p><div className="enquiry-intro-rule"/><span className="enquiry-intro-label">A conversation is all it takes</span><a href="mailto:info@cubixtop.com" className="enquiry-intro-email">info@cubixtop.com <ArrowUpRight size={18}/></a><div className="enquiry-quick-links"><a href="tel:+919481317929"><Phone size={16}/>Call us</a><a href="https://wa.me/919481317929" target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>WhatsApp</a></div><span className="enquiry-intro-phone">+91 9481 317 929</span></div></aside><div className="enquiry-form-panel"><button onClick={close} className="modal-close" aria-label="Close enquiry"><X size={21}/></button><span className="eyebrow">Let’s work together</span><h2 id="enquiry-title">What can we help<br/>you build?</h2><p className="enquiry-form-subtitle">A few details to start a great conversation.</p>{open&&<EnquiryForm service={service}/>}</div></div></dialog>;
}
