import {pageMetadata} from '@/lib/seo';
import {serviceImages} from '@/lib/service-images';
import {Content,CmsImage} from '@/components/Cms';
import {getService} from '@/lib/data';
import {notFound} from 'next/navigation';
import EnquiryButton from '@/components/EnquiryButton';
import Link from 'next/link';
export default async function Service({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=await getService(slug);if(!s)notFound();const photo=serviceImages[s.slug]||serviceImages['it-infrastructure-and-networking'];return <main><section className="page-hero photo-banner"><CmsImage id={`services.photo.${s.slug}`} src={photo.src} alt={photo.alt} className="page-banner-photo"/><div className="wrap"><Link href="/services" className="eyebrow light"><Content id="service-detail.text1">← All services</Content></Link><h1 className="display mt-5">{s.title}</h1><p>{s.short_description}</p></div></section><section className="section"><div className="wrap"><CmsImage id={`services.photo.${s.slug}`} src={photo.src} alt={photo.alt} className="service-detail-photo"/></div><div className="wrap contact-layout"><div><span className="eyebrow"><Content id="service-detail.text2">A solution that fits</Content></span><h2 className="section-title"><Content id="service-detail.text3">Let’s get your</Content><br/><Content id="service-detail.text4">business moving.</Content></h2><p className="lead"><Content id="service-detail.intro">Tell us your requirements. We’ll clarify the scope and help you plan the next steps.</Content></p>{s.description&&<p className="lead whitespace-pre-line mt-6">{s.description}</p>}<div className="principles"><div><h3><Content id="service-detail.text5">01 / Understand</Content></h3><p><Content id="service-detail.text6">Share your current setup, goals and requirements.</Content></p></div><div><h3><Content id="service-detail.text7">02 / Plan</Content></h3><p><Content id="service-detail.text8">Discuss a suitable approach, scope and timeline with our team.</Content></p></div></div></div><div className="enquiry-invite"><h2 className="section-title"><Content id="service-detail.text9">Start a conversation.</Content></h2><p className="lead mb-8"><Content id="service-detail.text10">Discuss your requirements with our team.</Content></p><EnquiryButton service={s.title}/></div></div></section></main>}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=await getService(slug);if(!service)return {title:'Service not found',robots:{index:false,follow:false}};return pageMetadata(service.title,service.short_description,'/services/'+slug);}
