import {NextResponse} from 'next/server';
import {z} from 'zod';
import {database,sameOrigin} from '@/lib/admin';
import {readJson,rateLimit,RequestError} from '@/lib/security';
import {mailConfigured,queueMail,deliverMail} from '@/lib/mail';
export const runtime='nodejs';
export const maxDuration=60;
const Schema=z.object({name:z.string().trim().min(2).max(120),email:z.string().trim().email().max(254).refine(v=>!/[\r\n]/.test(v)),phone:z.string().trim().regex(/^[+\d ()-]{6,30}$/),message:z.string().trim().min(3).max(3000),service:z.string().trim().max(160).optional(),website:z.string().max(200).optional()});
export async function POST(req:Request){if(!sameOrigin(req))return NextResponse.json({error:'Please refresh this page and submit again from the website.'},{status:403});try{const body=Schema.parse(await readJson(req));if(body.website)return NextResponse.json({error:'Unable to submit this enquiry.'},{status:400});const limited=await rateLimit(req,'enquiry');if(limited)return limited;if(!mailConfigured())return NextResponse.json({error:'Online enquiries are temporarily unavailable. Please email info@cubixtop.com or call +91 9481 317 929.'},{status:503});const reference=`CBX-ENQ-${new Date().getFullYear()}-${crypto.randomUUID()}`;const record={reference_number:reference,name:body.name,email:body.email,phone:body.phone,message:body.message,service_label:body.service||'General enquiry'};const {error}=await database().from('enquiries').insert(record);if(error)throw error;await queueMail(record);const delivered=await deliverMail(reference);return NextResponse.json({ok:true,reference,emailDelivery:delivered?'sent':'pending'},{status:delivered?200:202});}catch(e){if(e instanceof RequestError)return NextResponse.json({error:e.message},{status:e.status});if(e instanceof z.ZodError)return NextResponse.json({error:({name:'Please enter your full name (at least two characters).',email:'Please enter a valid email address.',phone:'Please use digits, spaces, +, brackets or hyphens for your phone number.',message:'Please enter a message between 3 and 3000 characters.',service:'Please select a valid service.'} as Record<string,string>)[String(e.issues[0]?.path[0])]||'Please check the form and try again.'},{status:400});return NextResponse.json({error:'Unable to complete your enquiry. Please email info@cubixtop.com.'},{status:503});}}
