create extension if not exists pgcrypto;
create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade,email text,full_name text,role text not null default 'ADMIN' check(role in ('ADMIN')),is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists pages(id uuid primary key default gen_random_uuid(),title text not null,slug text unique not null,page_type text default 'STANDARD',status text default 'DRAFT' check(status in('DRAFT','PUBLISHED')),seo_title text,seo_description text,seo_keywords text,og_image_url text,canonical_url text,indexable boolean default true,created_at timestamptz default now(),updated_at timestamptz default now(),published_at timestamptz);
create table if not exists page_sections(id uuid primary key default gen_random_uuid(),page_id uuid references pages(id) on delete cascade,section_type text not null,title text,subtitle text,content jsonb default '{}'::jsonb,display_order int default 0,is_visible boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists services(id uuid primary key default gen_random_uuid(),title text not null,slug text unique not null,short_description text,description text,icon text,hero_image_url text,featured boolean default false,active boolean default true,display_order int default 0,seo_title text,seo_description text,seo_keywords text,og_image_url text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists service_features(id uuid primary key default gen_random_uuid(),service_id uuid references services(id) on delete cascade,title text not null,description text,icon text,display_order int default 0);
create table if not exists service_process_steps(id uuid primary key default gen_random_uuid(),service_id uuid references services(id) on delete cascade,step_number int,title text,description text,display_order int default 0);
create table if not exists service_faqs(id uuid primary key default gen_random_uuid(),service_id uuid references services(id) on delete cascade,question text,answer text,display_order int default 0,active boolean default true);
create table if not exists media(id uuid primary key default gen_random_uuid(),file_name text,storage_path text,public_url text,mime_type text,file_size bigint,alt_text text,caption text,created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists enquiries(id uuid primary key default gen_random_uuid(),reference_number text unique not null,name text not null,company text,email text not null,phone text not null,service_id uuid references services(id),service_label text,message text not null,preferred_contact text,status text default 'NEW' check(status in('NEW','CONTACTED','IN_PROGRESS','QUALIFIED','CLOSED','SPAM')),source_page text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists enquiry_notes(id uuid primary key default gen_random_uuid(),enquiry_id uuid references enquiries(id) on delete cascade,note text not null,created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists site_settings(id uuid primary key default gen_random_uuid(),setting_group text,setting_key text,setting_value jsonb default '{}'::jsonb,updated_by uuid references auth.users(id),updated_at timestamptz default now(),unique(setting_group,setting_key));
create table if not exists navigation_items(id uuid primary key default gen_random_uuid(),label text,url text,parent_id uuid references navigation_items(id),display_order int default 0,open_new_tab boolean default false,active boolean default true);
create table if not exists social_links(id uuid primary key default gen_random_uuid(),platform text,url text,display_order int default 0,active boolean default true);
create table if not exists audit_logs(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id),action text,entity_type text,entity_id uuid,old_values jsonb,new_values jsonb,created_at timestamptz default now());

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles p where p.id=auth.uid() and p.role='ADMIN' and p.is_active=true); $$;

alter table profiles enable row level security; alter table pages enable row level security; alter table page_sections enable row level security; alter table services enable row level security; alter table service_features enable row level security; alter table service_process_steps enable row level security; alter table service_faqs enable row level security; alter table media enable row level security; alter table enquiries enable row level security; alter table enquiry_notes enable row level security; alter table site_settings enable row level security; alter table navigation_items enable row level security; alter table social_links enable row level security; alter table audit_logs enable row level security;
create policy "public published pages" on pages for select using(status='PUBLISHED'); create policy "public visible sections" on page_sections for select using(is_visible=true and exists(select 1 from pages where pages.id=page_id and status='PUBLISHED')); create policy "public active services" on services for select using(active=true); create policy "public service features" on service_features for select using(exists(select 1 from services s where s.id=service_id and s.active)); create policy "public process" on service_process_steps for select using(exists(select 1 from services s where s.id=service_id and s.active)); create policy "public faqs" on service_faqs for select using(active=true and exists(select 1 from services s where s.id=service_id and s.active)); create policy "public nav" on navigation_items for select using(active=true); create policy "public social" on social_links for select using(active=true);
create policy "admin profiles" on profiles for all using(public.is_admin()) with check(public.is_admin()); create policy "admin pages" on pages for all using(public.is_admin()) with check(public.is_admin()); create policy "admin sections" on page_sections for all using(public.is_admin()) with check(public.is_admin()); create policy "admin services" on services for all using(public.is_admin()) with check(public.is_admin()); create policy "admin features" on service_features for all using(public.is_admin()) with check(public.is_admin()); create policy "admin process" on service_process_steps for all using(public.is_admin()) with check(public.is_admin()); create policy "admin faqs" on service_faqs for all using(public.is_admin()) with check(public.is_admin()); create policy "admin media" on media for all using(public.is_admin()) with check(public.is_admin()); create policy "admin enquiries" on enquiries for select using(public.is_admin()); create policy "admin enquiries update" on enquiries for update using(public.is_admin()); create policy "admin notes" on enquiry_notes for all using(public.is_admin()) with check(public.is_admin()); create policy "admin settings" on site_settings for all using(public.is_admin()) with check(public.is_admin()); create policy "admin nav" on navigation_items for all using(public.is_admin()) with check(public.is_admin()); create policy "admin social" on social_links for all using(public.is_admin()) with check(public.is_admin()); create policy "admin audit" on audit_logs for select using(public.is_admin());

insert into services(title,slug,short_description,display_order) values
('Cloud Operations & Setup','cloud-operations-and-setup','Cloud setup, migration and operational support.',1),('Laptop Repair & Service','laptop-repair-and-service','Professional laptop diagnostics and service.',2),('Desktop Repair & Service','desktop-repair-and-service','Desktop support, upgrades and repair.',3),('iMac Repair & Service','imac-repair-and-service','iMac diagnostics and service.',4),('MacBook Repair & Service','macbook-repair-and-service','MacBook diagnostics and service.',5),('Customized Website Design','customized-website-design','Custom responsive websites for your business.',6),('Custom Application Development','custom-application-development','Purpose-built business applications.',7),('Hosting Solutions','hosting-solutions','Managed hosting solutions.',8),('Email Solutions','email-solutions','Business email setup and support.',9),('Mobile Repair & Service','mobile-repair-and-service','Mobile device repair and support.',10),('Electrical Services','electrical-services','Business electrical services.',11),('CCTV Installation & Repair','cctv-installation-and-repair','CCTV installation, maintenance and repair.',12),('Interior Design Services','interior-design-services','Functional commercial interior solutions.',13) on conflict(slug) do nothing;
insert into pages(title,slug,status,page_type) values ('Home','home','PUBLISHED','HOME'),('About','about','PUBLISHED','STANDARD'),('Services','services','PUBLISHED','SERVICES'),('Contact','contact','PUBLISHED','CONTACT'),('Privacy Policy','privacy-policy','DRAFT','LEGAL'),('Terms','terms','DRAFT','LEGAL') on conflict(slug) do nothing;