begin;
insert into public.services(title,slug,short_description,description,display_order,active) values
('IT AMC & Managed Support','it-amc-and-managed-support','Annual maintenance and ongoing support for your company’s IT infrastructure and software.','Keep everyday operations running with an annual maintenance contract covering business IT systems, preventive maintenance, software support and technical assistance. Scope and support arrangements are agreed around your company’s requirements.',1,true),
('IT Infrastructure & Networking','it-infrastructure-and-networking','Business networks, servers and workplace IT, planned and managed for reliable operations.','Plan, set up and maintain the systems your business depends on, from office networks and Wi-Fi to servers and employee workstations.',2,true),
('Business Software Solutions','custom-application-development','Custom applications, software integration and workflow automation for your business.','Build and connect business applications around your workflows. Discuss custom development, system integration and software support with our team.',3,true),
('Cloud & Business Email','cloud-operations-and-setup','Cloud setup, migration, hosting and business email under one technology partner.','Bring your business systems to the cloud with setup, migration and operational support. We help you plan hosting and email solutions suited to your team.',4,true),
('Cybersecurity & Backup','cybersecurity-and-backup','Endpoint protection, access controls and backup solutions to support business continuity.','Strengthen your IT environment with practical security controls, endpoint protection and backup planning. We help identify requirements and implement suitable solutions.',5,true),
('Website & Digital Solutions','customized-website-design','Professional websites and digital platforms built around your company’s goals.','Create a clear, responsive online presence with a website tailored to your business, with ongoing hosting and maintenance options.',6,true)
on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,description=excluded.description,display_order=excluded.display_order,active=excluded.active;
update public.services set active=false where slug in ('laptop-repair-and-service','desktop-repair-and-service','imac-repair-and-service','macbook-repair-and-service','hosting-solutions','email-solutions','mobile-repair-and-service','electrical-services','cctv-installation-and-repair','interior-design-services');
commit;
